# -*- coding: utf-8 -*-
"""Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAmCScALRLXMBgzeVNF1hB08devSISFm
"""

#Additions
def add(x,y):
  return x+y
#substraction
def subtract(x,y):
  return x-y
#division
def divide(x,y):
  return x/y

#division
def multiply(x,y):
  return x*y

print('Select Operation')
print('1.Add')
print('2.Subtract')
print('3.Divide')
print('4.Multiply')

while True:
  choice=input('Enter the Choice (1/2/3/4):')

  if choice in ('1','2','3','4'):
       num1= float(input("Enter first number:"))
       num2= float(input("Enter Second number:"))

       if choice == '1':
          print(num1,'+',num2,'=',add(num1,num2))

       elif choice == '2':
          print(num1,'-',num2,'=',subtract(num1,num2))

       elif choice =='3':
          print(num1,'/',num2,'=',divide(num1,num2))

       elif choice =='4':
          print(num1,'*',num2,'=',multiply(num1,num2))
       break
  else:
    print("Invalid Input")